---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.14
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: cedab0bd232290c2606c28ef7087106fc1a74f9a
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 02d6bfdc3113e2aeb9a52dd108144948dabe81b9
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: ed410027d243b764b623be1c76dd6ded55e6fd19
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: b653d56d561171c10049064d5a17861d97aac843
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 143048f718128e6bc0d0b5413055abadb7721b38
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 5ee85f736d0c6dc3ab45e7a0a57c612bf25c2ad4
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 5f67ea58d9489b8ad9fc06d4f89d347727e5fe9e
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: e68a5a38240f0f26d34bcad38c1cd0de8c7ada95
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 1294d44e572a250673a30328e8bf0a1ea0c295b5
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 1e4d12efb7ae37c4dc9b792336322e69dbb2a177
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 2740d97374ba559526b0c07df0bb31384f70cb2b
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: a72f824b7e4165765152c4ebd4c47e98d6b8c94e
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 71db6ce79dcdf1dada24c07303cff5e2aee997e2
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 97efd1ef35d33f60c2edf6b9dcbf81ce808693e6
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: f4d500419482e0a53cf35a34cd8864e5f0864d96
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
