#!/bin/bash

# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# deb opensearch-dashboards prerm script

set -e

echo "Running OpenSearch-Dashboards Pre-Removal Script"

# Stop existing service
if command -v systemctl >/dev/null && systemctl is-active opensearch-dashboards.service >/dev/null; then
    echo "Stop existing opensearch-dashboards.service"
    systemctl --no-reload stop opensearch-dashboards.service
fi

exit 0
