---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.1
ci:
  image:
    name: opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '1.3'
    checks:
      - gradle:publish
      - gradle:properties:version
