---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 'replace'
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 'replace'
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 'replace'
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 'replace'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
