---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 1.3.20
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 6c40db04510f4d8f47f77e23605c2dcfb085bc4b
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 7093ec2d8b6a65da110e11ae002ed8c64fc19e06
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 288070c248e266d58b33f879245263d484568bcf
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 0648b20307942002b4b9db989c33e52594f5db4e
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: af5c0966d8c96877b36c19a2208b29d8ae8a6a6d
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: c1c079f6a42ddf4534ebeb757707d4cc7df4b762
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: ff82f714e706fb4d511d41931664cd51b08ac877
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 06f01f1d9284b1898a020836caa7dfb25e91bf75
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: e3e924d5becd4c9b442e1cf7adcb8dab7dd0c8c1
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 7ca4cf480e2a8b4d48afd79a13878cedf9e24a88
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 1359e8cc8a19c13338508df14f17e596306cf719
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 47c6df905924acaea7fe580f3c8884d33d23bc0e
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 8584ba03b8c380f79d366a82fbbe78c5ea44faad
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 9aa4f082769b40afade53fad288175984a2b3bf2
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: be2c18fca0488e08f57ae05001fc91d04a684e33
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
