---
schema-version: '1.2'
build:
  name: OpenSearch
  version: 3.6.0
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: e2270fccb65fe4d49b58c004f4ddb17388866a5e
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: a686a58bd20e6e3451ce2cb241cfc15c848d6a5a
    platforms:
      - linux
      - windows
  - name: opensearch-learning-to-rank-base
    repository: https://github.com/opensearch-project/opensearch-learning-to-rank-base.git
    ref: 37f64eb388284109ea155d193cb4f01e6789f8a5
    platforms:
      - linux
      - windows
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: 2bcc23e51a47432e396e8a25b52b6f60f3077d53
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 014d31e4f92d1dfeb39d8cfec5218e409e29c4b2
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 484991461a9c2ee1001746fb949478e5b0905fa7
    platforms:
      - linux
      - windows
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: f7f43f50d2c52685a2e0f5354a8edd5f6a9ee734
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 77748fcf0540a4d3cafeabae2016fb13f9a746b9
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - security
      - custom-codecs
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 4d81c82efabb33da7bd5b18a1ab48d1db3600aee
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 3106a9ae2525742f04f9bf257fc015a5b373900e
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: a26f87fb679384f7559856ecd4d39bd215dac222
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: e35467f1f975fbf59891da7a314ec366dc635888
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 7f0976d82c9a06597e2d7719c0562fa67e4ec585
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: 7f0976d82c9a06597e2d7719c0562fa67e4ec585
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 8abc02bb147d01d67d8883c0fd36759415382867
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 17bc6103ac785a5edf0afd30e6b3fc9c54c263d5
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: b602686daf19536951c5cf490520620e4ad36d0a
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - geospatial
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 6b4dd17df337b1c53a0c30285bada1452cc3efaa
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 7ad281081ad59c4b35062f253bbb9a33048d40c2
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: b8ed308f127c2be394802cc9a4c5dac7eb0ddc93
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 9a3cbac9a82f0be5cd5ebe7d9a04a6e309e0cdeb
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - alerting
      - job-scheduler
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: f3286ac1a41af858cfac057a5b68bfbfa0e4af5f
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 819d1cc0eddb953c7d82cf7595b32e867b6d2c13
    platforms:
      - linux
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: 22bdb8c89a9f8b8d7a3bb947c9f4de6898fc4f44
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - opensearch-remote-metadata-sdk
      - ml-commons
      - k-NN
      - neural-search
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: d9e2e8b97152456e783378ed0e43d65fed1b391f
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
  - name: query-insights
    repository: https://github.com/opensearch-project/query-insights.git
    ref: 76558e829c49b9363cd5994784af3aea8bcdfd01
    platforms:
      - linux
      - windows
  - name: opensearch-system-templates
    repository: https://github.com/opensearch-project/opensearch-system-templates.git
    ref: 145ea6d83c666c34f7de1cefa3763a5f6322da56
    platforms:
      - linux
      - windows
  - name: user-behavior-insights
    repository: https://github.com/opensearch-project/user-behavior-insights.git
    ref: abb82e6eabb4aacee5a2558ab713e4f2d1374cd4
    platforms:
      - linux
      - windows
  - name: search-relevance
    repository: https://github.com/opensearch-project/search-relevance.git
    ref: 39de10a1adf5c146744fdf1888336abc617bcba9
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - neural-search
      - k-NN
      - ml-commons
      - user-behavior-insights
