---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.2.5
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '1.2'
    checks:
      - gradle:publish
      - gradle:properties:version
