---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.10
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: b2150b9f6f6c8a15059ef415d3e24bdedd3e253c
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: c224695d6250ca8f96869773c61d86bbf0972a7d
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 019acf326223e0d657cf94871a2930addcfdd4dd
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: b456af60afd11a74ae95378e138e0ba5803ff2df
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 2be0f46878b192b954c53b57b14f4756c8b8364d
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: e1592dd601013957732d32658740efd051f09c35
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: b679711a29d4954912b6ad90059677062f2ec7ba
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 9cef2aa75d1d8a2b3c13a7bbb0adc4ba609812f3
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: b9d18f818fec38d38632731da11ad0ba164355eb
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 2aad6dc346e6fda7579d21f35cde3543b3a5ed11
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 87c8e468f4c47bea0a140b52e39197aef4ff45ba
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 8fb7684ae4d336d9f60c51c009f57f2408dcc86d
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: d9ce057608b85afc552631d2e19aef6ab2480817
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: f56a4cabb5cf34690c7366af21d7fc4b750892d4
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: ecb2f8c157edf73ef655fc5c3f6791cc012db992
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
