---
schema-version: '1.0'
name: OpenSearch
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: asynchronous-search
    integ-test:
      test-configs:
        - with-security
        - without-security

  - name: ml-commons
    integ-test:
      test-configs:
        - with-security
        - without-security
