---
schema-version: '1.2'
build:
  name: OpenSearch
  version: 3.3.0
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-24
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-24
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-24
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-24
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 5e7dac44e21a980befd29568603aa6b28a3c1fd0
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 0568e91294bb0f915c846415437576ed60924518
    platforms:
      - linux
      - windows
  - name: opensearch-learning-to-rank-base
    repository: https://github.com/opensearch-project/opensearch-learning-to-rank-base.git
    ref: 3a1343f5fce88857987056957a36467e8b10672f
    platforms:
      - linux
      - windows
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: 9031f6adc1211345898a0e3ff0646d012b73795d
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: a05ebbc40b43d3043f6d7986f45620ff961a4e4e
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: aee54a8ca2a6cc596cb1e490be1e9fa240286246
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: ad134812a15682bf9968bb7aed4814fedcf2f568
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: ce2d1931b62b8337882e001770e9b45c62035e01
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 5bbe925d91816b998b9a472d2218f9102367b843
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: dbaac3d903938adc027efd1cc5933ef145f4aa39
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: e46b9abff788a8df0eb57e4d3e84b86126f85253
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: adca9cb7655368986ddf39cccd5329a8ef168f47
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: adca9cb7655368986ddf39cccd5329a8ef168f47
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: cdcccbd76c172d5aeb3bf8a411faf292ad09b09a
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 9a227c8dd0150cc67976066d1a52e533398a2ae1
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 378d0761ae524559d114af3985854fb90bcb408a
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - geospatial
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 3ae66d4a322d2ae8dbce3e69724aa69f9452abff
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 6044800595a287f3272953fb2e9500764ef76564
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: d86ff0d145108ce8fa8974ac201d085c20060d6d
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 54a6e59885b8c0e8eacedecbf289f065385a7ee8
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - alerting
      - job-scheduler
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 792edf88fb28ee86538d03edf6cf016497fcbe28
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 4e3d11a23226ee76f12e680a2eb2773f6f5c0973
    platforms:
      - linux
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: abeca73da3f10ac6e765a4609ec743ca9908965d
    platforms:
      - linux
      - windows
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: 32c6a7d9904e8cc6c5e0c88e238324ec731173c4
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - opensearch-remote-metadata-sdk
      - ml-commons
      - k-NN
      - neural-search
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: 1f866c0158fe468ac7cf059759b0a08f5190370a
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
  - name: query-insights
    repository: https://github.com/opensearch-project/query-insights.git
    ref: f0e4e7fd44e27e9e159f6f7c3b3b615bbb53b1fa
    platforms:
      - linux
      - windows
  - name: opensearch-system-templates
    repository: https://github.com/opensearch-project/opensearch-system-templates.git
    ref: c78b78053dd73e21478beef6877da0ca40899d6a
    platforms:
      - linux
      - windows
  - name: user-behavior-insights
    repository: https://github.com/opensearch-project/user-behavior-insights.git
    ref: e1cd18719a3d38656b403e0d9c2ecfa0e0fefbfd
    platforms:
      - linux
      - windows
  - name: search-relevance
    repository: https://github.com/opensearch-project/search-relevance.git
    ref: 6db5ba11cfbdb5c52f9d79ae0b1229881e45f2ce
    platforms:
      - linux
      - windows
