pipeline {
    agent none
    triggers {
      parameterizedCron '''
        H */2 * * * %INPUT_MANIFEST=1.1.0/opensearch-dashboards-1.1.0.yml
      '''
    }
    stages {
        stage('parameters') {
            steps {
                script {
                    properties([
                            parameters([
                                    string(
                                            defaultValue: '',
                                            name: 'INPUT_MANIFEST',
                                            trim: true
                                    )
                            ])
                    ])
                }
            }
        }
        stage('build') {
            parallel {
                stage('build-x64') {
                    agent {
                        docker {
                            label 'Jenkins-Agent-al2-x64-c54xlarge-Docker-Host'
                            image 'opensearchstaging/ci-runner:centos7-x64-arm64-jdk14-node10.24.1-cypress6.9.1-20211005'
                            alwaysPull true
                        }
                    }
                    steps {
                        script {
                            build()
                        }
                    }
                    post() {
                        always {
                            cleanWs disableDeferredWipeout: true, deleteDirs: true
                        }
                    }
                }
            }
            post() {
                success {
                    node('Jenkins-Agent-al2-x64-c54xlarge-Docker-Host') {
                        publishNotification(":white_check_mark:", "Successful Build", "\n${getAllJenkinsMessages()}")
                    }
                }
                failure {
                    node('Jenkins-Agent-al2-x64-c54xlarge-Docker-Host') {
                        publishNotification(":warning:", "Failed Build", "")
                    }
                }
            }
        }
    }
}

void build() {
    git url: 'https://github.com/opensearch-project/opensearch-build.git', branch: 'main'

    sh "./build.sh manifests/$INPUT_MANIFEST"

    script { manifest = readYaml(file: 'builds/manifest.yml') }

    def artifactPath = "${env.JOB_NAME}/${manifest.build.version}/${env.BUILD_NUMBER}/${manifest.build.platform}/${manifest.build.architecture}";
    def BASE_URL = PUBLIC_ARTIFACT_URL + artifactPath;

    sh "./assemble.sh builds/manifest.yml --base-url ${BASE_URL}"

    withAWS(role: 'opensearch-bundle', roleAccount: "${AWS_ACCOUNT_PUBLIC}", duration: 900, roleSessionName: 'jenkins-session') {
        s3Upload(file: 'builds', bucket: "${ARTIFACT_BUCKET_NAME}", path: "${artifactPath}/builds")
        s3Upload(file: "dist", bucket: "${ARTIFACT_BUCKET_NAME}", path: "${artifactPath}/dist")
    }

    addJenkinsMessage("${BASE_URL}/builds/manifest.yml\n" +
                      "${BASE_URL}/dist/manifest.yml")
}

/** Publishes a notification to a slack instance*/
void publishNotification(icon, msg, extra) {
    withCredentials([string(credentialsId: 'BUILD_NOTICE_WEBHOOK', variable: 'TOKEN')]) {
        sh("""curl -XPOST --header "Content-Type: application/json" --data '{"result_text": "$icon ${env.JOB_NAME} [${env.BUILD_NUMBER}] $msg ${env.BUILD_URL}\nManifest: ${INPUT_MANIFEST} $extra"}' """ + "$TOKEN")
    }
}

/** Add a message to the jenkins queue */
void addJenkinsMessage(message) {
    writeFile(file: "notifications/${STAGE_NAME}.msg", text: message)
    stash(includes: "notifications/*" , name: "notifications-${STAGE_NAME}")
}

/** Load all message in the jenkins queue and append them with a leading newline into a mutli-line string */
String getAllJenkinsMessages() {
    script {
        // Stages must be explicitly added to prevent overwriting
        // See https://ryan.himmelwright.net/post/jenkins-parallel-stashing/
        def stages = ['build-x64']
        for (stage in stages) {
            unstash "notifications-${stage}"
        }

        def files = findFiles(excludes: '', glob: 'notifications/*')
        def data = ""
        for (file in files) {
            data = data + "\n" + readFile (file: file.path)
        }

        // Delete all the notifications from the workspace
        dir('notifications') {
            deleteDir()
        }
        return data
    }
}
