---
schema-version: '1.1'
name: OpenSearch
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: '-e JAVA_HOME=/opt/java/openjdk-24 -u 1000 --cpus 4 -m 16g'
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: '-e JAVA_HOME=/opt/java/openjdk-24 --entrypoint=/usr/lib/systemd/systemd -u root --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host --cpus 4 -m 16g'
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-systemd-base-integtest-v1
        args: '-e JAVA_HOME=/opt/java/openjdk-24 --entrypoint=/usr/lib/systemd/systemd -u root --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host --cpus 4 -m 16g'
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: '-u ContainerAdministrator'
components:
  - name: OpenSearch
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: opensearch.yml
  - name: alerting
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        plugins.destination.host.deny_list:
          - 10.0.0.0/8
          - 127.0.0.1
    bwc-test:
      test-configs:
        - with-security
  - name: anomaly-detection
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: flow-framework
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: asynchronous-search
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: cross-cluster-replication
    integ-test:
      topology:
        - cluster_name: leader
          data_nodes: 2
        - cluster_name: follower
          data_nodes: 2
      test-configs:
        - with-security
        - without-security
  - name: geospatial
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: geospatial.yml
  - name: index-management
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        path.repo:
          - /tmp
    bwc-test:
      test-configs:
        - with-security
    smoke-test:
      test-spec: index-management.yml
  - name: k-NN
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        node.attr.knn_cb_tier: integ
        path.repo:
          - /tmp
          - logs
    smoke-test:
      test-spec: k-NN.yml
  - name: ml-commons
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: ml-commons.yml
  - name: opensearch-learning-to-rank-base
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: opensearch-learning-to-rank-base.yml
  - name: neural-search
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: neural-search.yml
  - name: notifications
    working-directory: notifications
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: opensearch-observability
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: opensearch-reports
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: security
    integ-test:
      test-configs:
        - with-security
    smoke-test:
      test-spec: security.yml
  - name: security-analytics
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: sql
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        script.context.field.max_compilations_rate: 1000/1m
        plugins.query.datasources.encryption.masterkey: 4fc8fee6a3fd7d6ca01772e5
    bwc-test:
      test-configs:
        - with-security
    smoke-test:
      test-spec: sql.yml
  - name: custom-codecs
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: skills
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: query-insights
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: opensearch-system-templates
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        opensearch.experimental.feature.application_templates.enabled: true
        cluster.application_templates.enabled: true
  - name: user-behavior-insights
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: search-relevance
    integ-test:
      test-configs:
        - with-security
        - without-security
    smoke-test:
      test-spec: search-relevance.yml
