pipeline {
    agent none
    environment {
        OPENSEARCH_BUILD_ID = "${BUILD_NUMBER}"
    }
    tools {
        jdk "JDK14"
        maven "maven-3.8.2"
    }
    triggers {
      parameterizedCron '''
        H */2 * * * %INPUT_MANIFEST=1.1.0/opensearch-1.1.0.yml
      '''
    }
    stages {
        stage('parameters') {
            steps {
                script {
                    properties([
                            parameters([
                                    string(
                                            defaultValue: '',
                                            name: 'INPUT_MANIFEST',
                                            trim: true
                                    )
                            ])
                    ])
                }
            }
        }
        stage('build') {
            agent {
                node {
                    label 'Jenkins-Agent-al2-x64-m5xlarge'
                }
            }
            stages {
                stage('build-snapshots') {
                    environment {
                        SNAPSHOT_REPO_URL = "https://aws.oss.sonatype.org/content/repositories/snapshots/"
                    }
                    agent {
                        node {
                            label 'Jenkins-Agent-al2-x64-m5xlarge'
                        }
                    }
                    steps {
                        script {
                            sh "rm -rf ~/.m2/"
                            git url: 'https://github.com/opensearch-project/opensearch-build.git', branch: 'main'
                            sh "./bundle-workflow/build.sh manifests/$INPUT_MANIFEST --snapshot"
                            withCredentials([usernamePassword(credentialsId: 'Sonatype', usernameVariable: 'SONATYPE_USERNAME', passwordVariable: 'SONATYPE_PASSWORD')]) {
                                sh('$WORKSPACE/publish/publish-snapshot.sh $WORKSPACE/artifacts/$ARTIFACT_PATH/maven')
                            }
                        }
                    }
                    post() {
                        always {
                            cleanWs disableDeferredWipeout: true, deleteDirs: true
                            sh "rm -rf ~/.m2/"
                        }
                    }
                }
                stage('build-x86') {
                    agent {
                        node {
                            label 'Jenkins-Agent-al2-x64-m5xlarge'
                        }
                    }
                    steps {
                        script {
                            build()
                        }
                    }
                    post() {
                        always {
                            cleanWs disableDeferredWipeout: true, deleteDirs: true
                            sh "rm -rf ~/.m2/"
                        }
                    }
                }
                stage('build-arm64') {
                    agent {
                        node {
                            label 'Jenkins-Agent-al2-arm64-m6gxlarge'
                        }
                    }
                    steps {
                        script {
                            build()
                        }
                    }
                    post() {
                        always {
                            cleanWs disableDeferredWipeout: true, deleteDirs: true
                            sh "rm -rf ~/.m2/"
                        }
                    }
                }
            }
            post() {
                success {
                    publishNotification(":white_check_mark:", "Successful Build")
                }
                failure {
                    publishNotification(":warning:", "Failed Build")
                }
            }
        }
    }
}

void build() {
    git url: 'https://github.com/opensearch-project/opensearch-build.git', branch: 'main'
    sh "./bundle-workflow/build.sh manifests/$INPUT_MANIFEST"
    sh './bundle-workflow/assemble.sh artifacts/manifest.yml'

    script { manifest = readYaml(file: 'artifacts/manifest.yml') }

    withAWS(role: 'opensearch-bundle', roleAccount: "${AWS_ACCOUNT_PUBLIC}", duration: 900, roleSessionName: 'jenkins-session') {
        s3Upload(file: 'artifacts', bucket: "${ARTIFACT_BUCKET_NAME}", path: "builds/${manifest.build.version}/${OPENSEARCH_BUILD_ID}/${manifest.build.architecture}")
        s3Upload(file: "bundle", bucket: "${ARTIFACT_BUCKET_NAME}", path: "bundles/${manifest.build.version}/${OPENSEARCH_BUILD_ID}/${manifest.build.architecture}")
    }
}

void publishNotification(icon, msg) {
    withCredentials([string(credentialsId: 'BUILD_NOTICE_WEBHOOK', variable: 'TOKEN')]) {
        sh """curl -XPOST --header "Content-Type: application/json" --data '{"result_text": "$icon ${env.JOB_NAME} [${env.BUILD_NUMBER}] $msg ${env.BUILD_URL}\nManifest: ${INPUT_MANIFEST}"}' $TOKEN"""
    }
}
