pipeline {
    agent none
    environment {
        TEST_RUN_ID = "${BUILD_NUMBER}"
    }
    parameters {
        string(name: 'opensearch_version')
        string(name: 'build_id')
        string(name: 'architecture')
    }
    stages {
        stage('Execute Tests') {
            steps {
                parallel (
                    IntegTests: {
                        build job: 'integ-test',
                        parameters: [
                            string(name: 'opensearch_version', value: "${params.opensearch_version}"),
                            string(name: 'build_id', value: "${params.build_id}"),
                            string(name: 'architecture', value: "${params.architecture}"),
                            string(name: 'test_run_id', value: "${TEST_RUN_ID}")
                        ]
                    },
                    PerfTests: {
                        build job: 'perf-test',
                        parameters: [
                            string(name: 'opensearch_version', value: "${params.opensearch_version}"),
                            string(name: 'build_id', value: "${params.build_id}"),
                            string(name: 'architecture', value: "${params.architecture}"),
                            string(name: 'test_run_id', value: "${TEST_RUN_ID}")
                        ]
                    },
                    BwcTests: {
                        build job: 'bwc-test',
                        parameters: [
                            string(name: 'opensearch_version', value: "${params.opensearch_version}"),
                            string(name: 'build_id', value: "${params.build_id}"),
                            string(name: 'architecture', value: "${params.architecture}"),
                            string(name: 'test_run_id', value: "${TEST_RUN_ID}")
                        ]
                    },
                    failFast: false)
            }
        }
        stage('Notify') {
            steps {
                echo "This step is stubbed. Its purpose is to notify different channels for successful build"
            }
            failFast false
        }
    }
}