---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.8
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2ac1c13e3877692bc9cbbab4c796d7244fe8486a
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 745bf040439394e4896030afda7a5b935944c4a5
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 32523e02e8b25f5f2f2e0f636ed717173e8a0070
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: fe3d31153c1334e63103d534bb786a8f4f362357
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 81d7b43f8e8bb73d0c73cb2713dd739e9effcd2a
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 160ef9645a12b22d3912dfbde15f9e0a3abc2d30
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: cbef85651e23cacc01ae05b8771d0e2415195177
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: bf3df8b6fa21f8db4602341a721cea19dacb964b
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: d828398c1d40ac0fea67682f2154d109f84c8320
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: df51076b25dd8be9e65e38a6d94ee140a6286e1c
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 5d5a70c4bbf42de271928ef9a7fc0827cb2677ee
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: da8da39cd0e84db11fb06a3b8c4171e8f8ece695
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 0773edf2d3bba57cc99f914982386e4f20c6e5cc
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: ea473423f0906772a39ea73dd3ef18ea5e0d0c73
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 7fabf39a82538aebea925f5ab901ffad2d1366a4
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
