---
schema-version: '1.0'
name: OpenSearch
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: index-management
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        path.repo: [/tmp]
    bwc-test:
      test-configs:
        - with-security
