---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 2.12.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: c85e75cb4db7946d7d4dfd0e7317c3f684e6345d
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 60a090e366bbb3c5a6605fdd22ce21a5525d2840
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: aaf09b0211df15dd74ff2756f2590c360b03486b
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 5e15d16d69c1f78396b787c19ed66884f61c7baa
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: abedfb6750707739828b093a931a4d9e0b182159
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 17ea68d46f831a843f4920e9ea419299605479e9
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: ee577a1729dec1b0bb05ddc3b767a54e6e905401
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: dd5b7a66803ee3f5387e2ef0de3b51cb952d9603
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: 0517a91999d35d2b8e799cde34a499ec264dbe1f
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 80fce319736825fa478988ae8d20c4de39c7cbf5
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
