name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report!
 - type: textarea
   id: what-happened
   attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
   validations:
    required: true
 - type: textarea
   id: to-Reproduce
   attributes:
    label: Steps to reproduce
    description: Tell us how to reproduce this issue
   validations:
    required: true
 - type: textarea
   id: screenshots
   attributes:
    label: Screenshots
    description: Attach the screenshots associated with this issue
    value: If applicable, add screenshots to help explain your problem.
 - type: textarea
   id: Host-Environment
   attributes:
    label: Host / Environment
    description: Hosts / Environment information to reproduce this bug
 - type: textarea
   id: logs
   attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
