---
name: On-board plugins to the distribution
description: On-board plugins to the distribution
title: '[On-boarding]: '
labels: [on-boarding, untriaged]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit on-boarding request!
  - type: textarea
    attributes:
      description: 'Provide the name of your plugin.'
      label: 'What is the name of your plugin?'
    id: plugin-name
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Provide the GitHub link for your repository.'
      label: 'What is the link to your GitHub repo?'
    id: Github-link
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'What is the targeted OpenSearch release version for this plugin?'
      label: 'Targeted release version'
    id: expected-release-version
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'If so, provide the link to the associated documentation PR. For information on contributing documentation, see [Contributing.md](https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md).'
      label: 'Does the plugin require documentation?'
    id: documentation
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Is this OpenSearch, OpenSearch-dashboards plugin?'
      label: 'What type of the plugin are we on-boarding?'
    id: Type
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'See the [on-boarding document](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#plugin-onboarding).'
      label: 'Did you read the on-boarding document?'
    id: document
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Does this plugin have necessary scripts to invoke integration and BWC tests?'
      label: 'Does this plugin has all the necessary automated tests?'
    id: tests
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Confirm that all the necessary reviews for this component has been completed.'
      label: 'Have you completed the required reviews including Security reviews, UX reviews?'
    id: reviews
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Do we need to enable any automated CVE scanning on this repo?'
      label: 'Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?'
    id: repo-scanning
    validations:
      required: true
  - type: textarea
    attributes:
      description: 'Add any additional context along with contact details for this component here.'
      label: 'Additional context'
    id: additional-context
