---
schema-version: '1.1'
name: OpenSearch
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: '-e JAVA_HOME=/opt/java/openjdk-21 -u 1000 --cpus 4 -m 16g'
components:
  - name: index-management
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        path.repo: [/tmp]
    bwc-test:
      test-configs:
        - with-security
