---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.4.1
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '2.4'
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: '2.4'
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
