---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 1.3.19
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 3ce0904c5e452a18ba343eecf04005bfd91b3249
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 211c19838bbd5be23e471d59e5f613d491aa6329
    checks:
      - gradle:publish
      - gradle:properties:version
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 53175b011dd6c92fe8681c5140bde828a9aef3d6
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: c647ea13b640cf48ebf87cc4a534ee6556c9e45a
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 05df353de9cee48de828fed825e41598c2ac7e4f
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 7cc894793c0ea8cdac01df5328b89d5bafeda69a
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 18c017b775b20cb2cb254a52dda09e3f4fde9171
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 1fa195478242864313994b37ca6cb59d649ee080
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: c4d98c122706b1ab5add15f867e9877f4b916a71
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: d172eabdc05ec3f7aebd9035474354c84446423b
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 1ebda2edf63f27b67ee0c7eb234ac726a93485c8
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 3f7de96d839a04d5cd83d46a4a1417666c190618
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 430a374a4b787e1ec8b4ea289539d779d1dfc4bd
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 332189c302420cd15afdfa3d4376800612a4e1f4
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: b8f5da3072404a5dca761e616dea52e96604a604
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
