---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.11.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: dc5128eaeb9e25356e93476772faef8236a87688
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: aaa4c2a061601105c62cbaf9838a0a4bd9986aa3
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 0a2fef228bb687995d2e3ddefa88ecf1e191ffd7
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: f807aa2997f02a7b92421be9266c0dabb41ea963
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 2a7f1b01589d893c0b1f153c4edc68295f85d0e5
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 8b6f2d7dc355a2e5508b40b9e1cdfa5500736852
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 5c3a3c2fab950abc368a2ab69f483f825c2284d2
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: bb84282ebb43ad30a6c7ff2a973ddfc777d26aba
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: 841f280217a529391ce0fe178cc119d6d44627b7
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: fd849a6a3aef63d7ae697416695e6b0458cd7816
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: fd849a6a3aef63d7ae697416695e6b0458cd7816
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: notifications
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: bd11e813ebd5ac002c3d34ed2c965325d5874b77
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 78c8c89f318ebee78a5f9ea398cafd9aea33e3fb
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 1b9fe1f6541a02d59f69759298352a44d6dbafe3
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-sql-plugin
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: e291c1cc8e84d1db727ecf3faf04ef30ebcf0d17
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 35d476461feba246a2eea705e75d99553b495d0c
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: f729cc019a35297875953f6bb6330730d4634b1b
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 848262e64ed8f7ea64dd4ad628284d88d17f0e77
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 905868eac14ae47cd8a0c27a9bbb6d0b59ef1c9b
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: d907f1986f76a390dbe6a856f41d61203cadb6e1
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: 486ed652b7de41c34d81d8d663ca02302fed78ae
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
