---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.11.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-rockylinux8-opensearch-build-v4
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2.x
    checks:
      - gradle:publish
      - gradle:properties:version
