---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 2.13.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 7ec678d1b7c87d6e779fdef94e33623e1f1e2647
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 937bc4ecdf5ff07a1087b259c330c9b361db5c32
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: d2bb21838c087c6331e53c7f696680931bfe8672
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 8f029ebc9753888d9009547e26cada1a71a81585
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: 328f501a85591ccc8b228ef9d95966cdb782832d
    platforms:
      - linux
      - windows
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: ae663a1f5dc0bec3cd1e1e43907336c5522100ae
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: b64bd49ff3d0fd0f3b6168add339b9000c6e91aa
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 493e394628e0c7598f32fc103e8470636115c06e
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: 52795807658f6e719f4c22147a54e0baca5c43dd
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: d7f36a416b5c16000f6e367c6c4a78e2c92e1093
    platforms:
      - linux
      - windows
    working_directory: notifications
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: d7f36a416b5c16000f6e367c6c4a78e2c92e1093
    platforms:
      - linux
      - windows
    working_directory: notifications
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: a488b1fee983d416a858a9dbbe10c6773413ee07
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 6383f7a1460925f5aaf5763487f04943c30ce543
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 89647c14f624320a26e30e04af865c9471189008
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: edb7cf2ff74fa4f04ae08a4969a657134fd2c891
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 68b350624db92ce494eb09416d5b3803fe4b9fe9
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: c0b737b20f61938ae2a2b1dfea6c3e2bbc16a636
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: d3af2426bc2b3697c3a854fb3b24a76ba333640a
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: fa8d1b3cf484a08e7526ceb2b53a97d9c49b82c4
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 6863a65449a1f05bf2c45c76a3359fd1950b930f
    platforms:
      - linux
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: 5c4e4cb7afd2db8299ac7e66cc80e82a7c670028
    platforms:
      - linux
      - windows
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: 478bb7eae139064b41f5af15712022a2f5415dc7
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: b61f8ee1233762c5bbc27207a8c66fc8ae622d75
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
