---
schema-version: '1.2'
build:
  name: OpenSearch
  version: 2.19.6
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 928e13c76f8211f83235f6e6a01efb0c1e963c6d
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 0127ccb1e61d0c1673c8e99473dc9958e48b5e4a
    platforms:
      - linux
      - windows
  - name: opensearch-learning-to-rank-base
    repository: https://github.com/opensearch-project/opensearch-learning-to-rank-base.git
    ref: f88df72c6a873db6a305cdf47f60d56dfdd70a17
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: 88d1fdd1ddd05e5d3d1652ba5a63a76fa7d4bb82
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 4061296a58ae8834a9800ac8c12df7c39fd4940f
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: ba39786024e6c26103046cbb81a844a724d1a335
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: bdf82f14811d8375806ec61176e678fc9171d765
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 0d53ca7eae50904a542862f000fb167f55a62fa3
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: d51f448aa4e7d8b7a72c776ceed16887abd83aeb
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: dcb9fbd5e00bba98054bae9ca1da655728618cf8
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: a2b92f338286e9b5a796f2ce890d964af5f7f2e3
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
      - job-scheduler
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 8f01b57de35ca7ccd336e236d845f6b2cc0662d7
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: 8f01b57de35ca7ccd336e236d845f6b2cc0662d7
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 6a931c13f21448f64ce4aca29d7eda3f2341f2fc
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 0e45ac16c4080cea98f071b9fdf710dba36f409f
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 027baa6c5a49186cc0ecdd73eef3a24411ed4576
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - job-scheduler
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 54b6df0cfad0433a5421ce5f6ad6f222f2e7e3d7
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 12440ce165e15976e8184697886ded807ad81c9a
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 08674956f8bfec996539c6b448a4fa2e49ce6b03
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - notifications-core
      - notifications
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: ca5e69ff330d138be8f3b9d10263a054af249272
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - alerting
      - job-scheduler
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 2c051cd420f9170fee22c119b59a931fbf1cfc6f
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 6730ea3eb3800a2f2773ffde1dd55a4faef48510
    platforms:
      - linux
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: a5953b25bf94345ecae863d2c77683dae25ea501
    platforms:
      - linux
      - windows
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: 019f693839f062193f8d9d9989ab97cf8457fcd5
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - opensearch-remote-metadata-sdk
      - ml-commons
      - k-NN
      - neural-search
      - job-scheduler
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: 7bebdf83089d4ac8bb335f96260fcb30be18d389
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
      - alerting
      - neural-search
      - k-NN
  - name: query-insights
    repository: https://github.com/opensearch-project/query-insights.git
    ref: f275c085c7700169be0d4156cca24c6026c1da5c
    platforms:
      - linux
      - windows
  - name: opensearch-system-templates
    repository: https://github.com/opensearch-project/opensearch-system-templates.git
    ref: 9f6642d86e774cb104c7eedbec5c3b8706ce4e4f
    platforms:
      - linux
      - windows
    depends_on:
      - custom-codecs
