---
schema-version: '1.2'
build:
  name: OpenSearch
  version: 2.19.6
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 97d3c13bf22a4a72ac11dc503fe44c97662b9161
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 5def2dec8ae3c69f516e3a4db451e4f393c43667
    platforms:
      - linux
      - windows
  - name: opensearch-learning-to-rank-base
    repository: https://github.com/opensearch-project/opensearch-learning-to-rank-base.git
    ref: f511086d7e7adb0816f97630dcedc1a36d63780f
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: df7a7ea6c49e6e33a2a13fee765d25f494a7c6cf
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 6a48ba4509d25e48a3fa07304143b151091f3b72
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 62c49afae03e12e348b5efcfbf90d44624b8e364
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: bf722153fd119f01bed31a0ec23607ff39469118
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: d6bd974d28ef4e692fea6ffed1a45643bb9c0021
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 7af8884f0638192500e6306f424e9658c52273d1
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 7552f90b77e576c2417472a3415bb20b8a6f6e56
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: a680d0af96b6484952c4b31923fbfce4a2818578
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
      - job-scheduler
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 6c1d09a84cbf30316c4e2fb5a1fe0c0edda592b2
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: 6c1d09a84cbf30316c4e2fb5a1fe0c0edda592b2
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: f33078e768f914d75e9c53f53e8447b8d8f5eb9e
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 69f8e3a53f5a8d3925f9eccf09379d3f8abe6006
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 9dc901e7e479e7928e739fb9f97165c5ea390bc4
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - job-scheduler
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: ee4890cca50f541b57cb1dccffebab9d7a48527d
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 8804372094051924a2686594f8929414f3ec15c4
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 7fa479a1abc9c363f50ca6e37928c446fc8ac3cc
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - notifications-core
      - notifications
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: aaba5111d7b540a56f45da86ceed3ac30578d683
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - alerting
      - job-scheduler
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: ee91d1ca1dac006cd32cc74399032ffb72baf2da
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: ee04398ac34b3c099b90471e923775a207cc5610
    platforms:
      - linux
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: 5d3706f553e056cb3e370b64bf7fdbde5bd88274
    platforms:
      - linux
      - windows
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: feec07fb5ba1bcf589cfe7df79786c263d2d98d5
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - opensearch-remote-metadata-sdk
      - ml-commons
      - k-NN
      - neural-search
      - job-scheduler
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: 7a2548f0048bb28b081d425f759f0eccd1800a7a
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
      - alerting
      - neural-search
      - k-NN
  - name: query-insights
    repository: https://github.com/opensearch-project/query-insights.git
    ref: 48f44b2029c7ba190165a1976f5a245ad882dda9
    platforms:
      - linux
      - windows
  - name: opensearch-system-templates
    repository: https://github.com/opensearch-project/opensearch-system-templates.git
    ref: 610971104a5b750d8b4790a56048381eb9c304f2
    platforms:
      - linux
      - windows
    depends_on:
      - custom-codecs
