---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 2.14.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 0f1da07407612163de07e668c782179b82a034ea
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 7531f1e853db28ca9deead97be053d58da7a7a9c
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 7f9a2b120d9c7ff3422705be1b8fe4e7959bbd2a
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 435856c919e4e92cf030fbdadc11bf87dd991543
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: bd1c99f2496c9671482a7177d906c661a2666b16
    platforms:
      - linux
      - windows
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 365ed5f86cc41c0736f42cec198a44ce8cded9ba
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 487ff81f29f3738b8ccaec92bc88fe8303a43576
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: fba960603bb10634ccba616fe061599014fa978c
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: c95fe26b21ea90537639beb17ab1cb1defc30550
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: dc8a208a3d978c337113543c65ffac04ba1fb7cb
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: dc8a208a3d978c337113543c65ffac04ba1fb7cb
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 8bd76309acdd7d8d45d292c6f53f67399d39e34b
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: c487fa37c54e2cdc10f56843efb6a0ebb60b3259
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: 7c7465c4318b06a00b56b11c026feab8a0496027
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: f8121394f960d46842437ebcbdd17c5bb3d3022b
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: be2cce3d08062831cd5c86a421bd93d6f45b84ab
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: cb4ff3ee639e57695ca24d2ad27b6f6bb6e41914
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: ddbe6eddf83e0a6fa8b0e896e3173ac08262da14
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: fa05d71719e01ae5376d570f6db7f08d3886497d
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 33e701d8070a8add7d14ae430880553adaa34d38
    platforms:
      - linux
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: df79b5d36f79e27a5a321bedc318f510a0f698b1
    platforms:
      - linux
      - windows
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: d94bc9461414d19a05a00c5eb85e2200f916faf1
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: eba9e1c2863891282de86af87af4310b5b6c4a78
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
