---
schema-version: '1.2'
build:
  name: OpenSearch
  version: 3.8.0
ci:
  image:
    linux:
      tar:
        name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
      deb:
        name: opensearchstaging/ci-runner:ci-runner-ubuntu2404-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
      rpm:
        name: opensearchstaging/ci-runner:ci-runner-almalinux8-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
    windows:
      zip:
        name: opensearchstaging/ci-runner:ci-runner-windows2019-opensearch-build-v1
        args: -e JAVA_HOME=/opt/java/openjdk-25
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: e5a3c5691be87af6c12dbe3e158c59c04ee72973
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 59bd871bc3b7b776e34629cca596880e0a0da5e2
    platforms:
      - linux
      - windows
  - name: opensearch-learning-to-rank-base
    repository: https://github.com/opensearch-project/opensearch-learning-to-rank-base.git
    ref: 8203333c611ec8fa710e52e5ec6e66960739e3c6
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: 74a0378e03948a0f646748cf3a016e8acc084860
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 63d36555a38427aeea3a13eb48d566a6edebe5ac
    platforms:
      - linux
      - windows
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 7891aeae2fc3e502ffe0f98c93822b645e939458
    platforms:
      - linux
      - windows
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: eb86a15095a2da6d12dbca01f4a87a505a6f0f5c
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: e157d018e7196a864d2904664e6fd8aaef8d53ea
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - security
      - custom-codecs
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 89eaddf4359adf0678d01cf1dfe586fe818a44ab
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 69ad00fb6beb4cdb962ef96aa095d5635557136a
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 694e8cb9565da1439fbe26e3c9339bde2be56c09
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
      - security
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: fc733c807f12cb40db890ba15e584046cd6a3c1b
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
      - job-scheduler
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 5b9868f3b1cb4a5933e5c2be45ef4fdc7bd4f6c7
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: 5b9868f3b1cb4a5933e5c2be45ef4fdc7bd4f6c7
    working_directory: notifications
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: d9da96acd208baa4cbfeb33e18720ccbf340f80d
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 2262792cd3f8f7b5c615f9973d0a1288c7ea80be
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: fe20ba69e3bb201183d2462bce37bf520cc3aa92
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - geospatial
      - job-scheduler
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: 8da1322ee3cd0e44402081bc58478e6326a5ea54
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: 49c8c2e579ec4b7abbf8e8f5ee683c5b73478b2f
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 10fe7b7f68805e138ef1bf336b8f7e68ff8fa5f4
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - notifications-core
      - notifications
      - sql
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 2061a2168a4a4c0acbf236100825c4f84d12c31a
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - alerting
      - job-scheduler
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 592e20171db2d385c67abf3e4c48bcf1555c6e3c
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 451c5c956e47182ab3b93cf3af4ad08a2e2cb0ac
    platforms:
      - linux
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: 2b114f50b708eda2615156318854936277da2a8c
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - opensearch-remote-metadata-sdk
      - ml-commons
      - k-NN
      - neural-search
      - job-scheduler
  - name: skills
    repository: https://github.com/opensearch-project/skills.git
    ref: 6a62f5584586bad8a8d55bbe3415414d5c3fda8c
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - anomaly-detection
      - sql
      - ml-commons
      - alerting
      - neural-search
      - k-NN
  - name: query-insights
    repository: https://github.com/opensearch-project/query-insights.git
    ref: a5bf00f1bbde5cb41f28041b3548ae2c0e0593a4
    platforms:
      - linux
      - windows
  - name: opensearch-system-templates
    repository: https://github.com/opensearch-project/opensearch-system-templates.git
    ref: 1e91340db293826c3d1e3c1ec41841de9d589c6a
    platforms:
      - linux
      - windows
    depends_on:
      - custom-codecs
  - name: user-behavior-insights
    repository: https://github.com/opensearch-project/user-behavior-insights.git
    ref: 8cf801542c1f1f74412bc9a2cbea563642cf2dc3
    platforms:
      - linux
      - windows
  - name: search-relevance
    repository: https://github.com/opensearch-project/search-relevance.git
    ref: 7115b27015186453467b52209aea3b672a1a3b40
    platforms:
      - linux
      - windows
    depends_on:
      - job-scheduler
      - neural-search
      - k-NN
      - ml-commons
      - user-behavior-insights
