---
schema-version: "1.0"
ci:
  image:
     name: "opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028"
     args: "-e JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot"
build:
  name: OpenSearch
  version: 1.2.3
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: "1.2"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: "1.2"
    checks:
      - gradle:publish
      - gradle:properties:version
