#!/bin/sh

# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# This wrapper script allows SystemD to feed a file containing a passphrase into
# the main OpenSearch startup script

if [ -n "$OPENSEARCH_KEYSTORE_PASSPHRASE_FILE" ] ; then
   echo "Find passphrase file, start opensearch with passphrase imported"
   exec /usr/share/opensearch/bin/opensearch "$@" < "$OPENSEARCH_KEYSTORE_PASSPHRASE_FILE"
else
   echo "No passphrase file found, start opensearch without importing the passphrase"
   exec /usr/share/opensearch/bin/opensearch "$@"
fi
