---
schema-version: "1.0"
ci:
  image:
     name: "opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028"
     args: "-e JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot"
build:
  name: OpenSearch
  version: 1.2.0
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: "1.x"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: "main"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: "main"
    platforms:
      - darwin
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
