---
schema-version: "1.0"
build:
  name: OpenSearch
  version: 1.2.0
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: "1.x"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: "main"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
