---
schema-version: "1.0"
build:
  name: OpenSearch
  version: 1.2.0
  jdk: "14"
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: "1.x"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: "main"
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: "main"
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version