components:
  # - name: index-management
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  - name: anomaly-detection
    integ-test:
      dependencies:
        - job-scheduler
        - alerting
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
  - name: asynchronous-search
    integ-test:
      dependencies:
        - job-scheduler
        - alerting
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
        - without-security
schema-version: '1.0'
