components:
  - name: index-management
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
  - name: anomaly-detection
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
  - name: asynchronous-search
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
        - without-security
  - name: sql
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
  - name: k-NN
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
schema-version: '1.0'
