components:
  - name: index-management
    integ-test:
      dependencies:
        - job-scheduler
        - alerting
      test-configs:
        - with-security
        - without-security
        - with-less-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
schema-version: '1.0'
