---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.15
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-11
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '1.3'
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: '1.3'
