name: bundle-workflow

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.7

    defaults:
      run:
        working-directory: ./bundle-workflow

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install --deploy --dev
      - name: Check for Sorted Imports
        run: |
          pipenv run isort --check .
      - name: Enforce Style Guide
        run: |
          pipenv run flake8 .
      - name: Run Type Checker
        run: |
          pipenv run mypy .
      - name: Run Tests with Coverage
        run: |
          pipenv run coverage run -m pytest --cov=./src --cov-report=xml
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          files: ./bundle-workflow/coverage.xml
