---
name: js-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          cache: npm
      - run: yarn install
      - run: yarn test -- --coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
