---
name: merge common changes

on:
  workflow_run:
    workflows:
      - Link Checker
      - yaml-lint
    types: completed
  workflow_dispatch:
  check_run:
  check_suite:
  pull_request_target:
  status:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: identify-triggering-pr
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const workflowRunId = context.payload.workflow_run.id;
            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: workflowRunId,
            });
            const trigger = workflowRun.data.event;
            console.log(JSON.stringify(workflowRun.data));

            return { "pr": workflowRun.data.?pull_requests[0].?number };

      - uses: peternied/discerning-merger@main
        if: steps.identify-triggering-pr.outputs.result != null
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.identify-triggering-pr.outputs.result.pr }}
          allowed-authors: |
            dependabot
            opensearch-trigger-bot
            peterzhuamazon
            bbarani
            gaiksaya
            rishabh6788
            zelinh
            jordarlu
            prudhvigodithi
            Divyaasm
            dblock
            tianleh
            peternied
          allowed-files: |
            manifests/*/*.yml
