---1
name: merge common changes1
1
on:1
  workflow_run:1
    workflows:1
      - Link Checker1
      - yaml-lint1
    types: completed1
1
jobs:1
  auto-merge:1
    runs-on: ubuntu-latest1
    steps:1
      - uses: actions/checkout@v41
1
      - id: identify-triggering-pr1
        uses: actions/github-script@v61
        with:1
          script: |1
            const { owner, repo } = context.repo;1
            const workflowRunId = context.payload.workflow_run.id;1
            console.log(JSON.stringify(context.payload));1
            const workflowRun = await github.rest.actions.getWorkflowRun({1
              owner,1
              repo,1
              run_id: workflowRunId,1
            });1
            const trigger = workflowRun.data.event;1
            return workflowRun.data?.pull_requests[0]?.number;1
1
      - uses: peternied/discerning-merger@main1
        if: steps.identify-triggering-pr.outputs.result != null1
        with:1
          token: ${{ secrets.GITHUB_TOKEN }}1
          pull-request-number: ${{ steps.identify-triggering-pr.outputs.result }}1
          allowed-authors: |1
            dependabot1
            opensearch-trigger-bot1
            peterzhuamazon1
            bbarani1
            gaiksaya1
            rishabh67881
            zelinh1
            jordarlu1
            prudhvigodithi1
            Divyaasm1
            dblock1
            tianleh1
            peternied1
          allowed-files: |1
            manifests/*/*.yml1
