---
name: merge common changes

on:
  workflow_run:
    workflows:
      - Link Checker
      - yaml-lint
    types: completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: find-triggering-pr
        uses: peternied/find-triggering-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peternied/discerning-merger@main
        if: steps.find-triggering-pr.outputs.pr-number != null
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find-triggering-pr.outputs.pr-number }}
          allowed-authors: |
            dependabot
            opensearch-trigger-bot
            peterzhuamazon
            bbarani
            gaiksaya
            rishabh6788
            zelinh
            jordarlu
            prudhvigodithi
            Divyaasm
            dblock
            tianleh
            peternied
          allowed-files: |
            manifests/*/*.yml
