---
name: merge common changes

on:
  workflow_dispatch:
  check_run:
  check_suite:
  pull_request_target: 

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peternied/discerning-merger@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: |
            dependabot
            opensearch-trigger-bot
            peterzhuamazon
            bbarani
            gaiksaya
            rishabh6788
            zelinh
            jordarlu
            prudhvigodithi
            Divyaasm
            dblock
            tianleh
            peternied
          allowed-files: |
            manifest/*/*.yml
