---
name: Increment OpenSearch Plugins Version

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  plugin-version-increment-sync:
    if: github.repository == 'opensearch-project/opensearch-build'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          # Adding the core repo OpenSearch for the label creation automation
          - {repo: OpenSearch}
          - {repo: alerting}
          - {repo: anomaly-detection}
          - {repo: asynchronous-search}
          - {repo: common-utils}
          - {repo: cross-cluster-replication}
          - {repo: geospatial}
          - {repo: index-management}
          - {repo: job-scheduler}
          - {repo: k-NN}
          - {repo: neural-search}
          - {repo: ml-commons}
          - {repo: notifications, path: notifications}
          - {repo: observability}
          - {repo: performance-analyzer}
          - {repo: performance-analyzer-rca}
          - {repo: reporting}
          - {repo: security}
          - {repo: security-analytics}
          - {repo: sql}
          - {repo: custom-codecs}
          - {repo: flow-framework}
          - {repo: skills}
          - {repo: query-insights}
          - {repo: opensearch-system-templates}
          - {repo: opensearch-remote-metadata-sdk}
          - {repo: opensearch-learning-to-rank-base}
          - {repo: search-relevance}
          - {repo: user-behavior-insights}
          - {repo: opensearch-jvector}
        branch:
          - '2.19'
          - 'main'
          - '3.7'
          - '3.8'
    steps:
      - name: Check out OpenSearch repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: opensearch-project/OpenSearch
          ref: ${{ matrix.branch }}
          persist-credentials: false

      - name: Fetch OpenSearch version
        run: |
          OPENSEARCH_VERSION=$(cat buildSrc/version.properties | grep opensearch | cut -d= -f2 | grep -oE '[0-9.]+')
          echo "OPENSEARCH_VERSION_NUMBER=$OPENSEARCH_VERSION" >> $GITHUB_ENV
          OPENSEARCH_VERSION=$OPENSEARCH_VERSION-SNAPSHOT
          echo "OPENSEARCH_VERSION=$OPENSEARCH_VERSION" >> $GITHUB_ENV

      - name: Get JDK version
        run: |
          OS_VERSION=${{ env.OPENSEARCH_VERSION_NUMBER }}
          OPENSEARCH_JAVA_VERSION_NUMBER=`curl -sSfL https://raw.githubusercontent.com/opensearch-project/opensearch-build/refs/heads/main/manifests/$OS_VERSION/opensearch-$OS_VERSION.yml | yq -r '.ci.image.linux.tar.args' | grep -oE 'openjdk-[0-9]*' | awk -F'-' '{ print $NF }'`
          echo "OPENSEARCH_JAVA_VERSION=$OPENSEARCH_JAVA_VERSION_NUMBER" >> $GITHUB_ENV

      - name: Set up JDK ${{ env.OPENSEARCH_JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ env.OPENSEARCH_JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Check out plugin repo
        if: ${{ matrix.entry.repo != 'OpenSearch' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: opensearch-project/${{ matrix.entry.repo }}
          ref: ${{ matrix.branch }}
          persist-credentials: false

      - name: Increment Version in ${{ matrix.entry.repo }}
        if: ${{ matrix.entry.repo != 'OpenSearch' }}
        run: |
          rm -rvf .git/hooks
          echo "OpenSearch Core repo version on branch ${{ matrix.branch }} is ${{ env.OPENSEARCH_VERSION_NUMBER }}"
          if [ ${{ matrix.entry.path }} ]; then
            echo "The gradle path is ${{ matrix.entry.path }}"
            cd ${{ matrix.entry.path }}
          fi
          ./gradlew updateVersion -DnewVersion=${{ env.OPENSEARCH_VERSION }}

      - name: Create Pull Request
        if: ${{ matrix.entry.repo != 'OpenSearch' }}
        id: cpr
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ secrets.OPENSEARCH_CI_BOT_TOKEN }}
          push-to-fork: opensearch-ci-bot/${{ matrix.entry.repo }}
          committer: opensearch-ci-bot <opensearch-infra@amazon.com>
          author: opensearch-ci-bot <opensearch-infra@amazon.com>
          commit-message: |
            Increment version to ${{ env.OPENSEARCH_VERSION }}

            Signed-off-by: opensearch-ci-bot <opensearch-infra@amazon.com>
          delete-branch: true
          branch: create-pull-request/${{ env.OPENSEARCH_VERSION }}
          title: '[AUTO] Increment version to ${{ env.OPENSEARCH_VERSION }}'
          body: |
            - Incremented version to **${{ env.OPENSEARCH_VERSION }}**.

      - name: Check outputs
        if: ${{ matrix.entry.repo != 'OpenSearch' }}
        run: |-
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
