name: Mark Stale PRs
on:
  schedule:
    - cron: '30 1 * * *''
permissions:
  pull-requests: write
jobs:
  mark-stale-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-label: 'stale'
          stale-pr-message: 'This PR is stalled because it has been open for 30 days with no activity.'
          days-before-pr-stale: 30
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

